### ISSUE TITLE
☂  [Routing samples] Simplify routing and navigation samples

### ISSUE THREAD

**Issue by ericwindmill** [flutter/samples#2514]
Currently routing is a core feature of two samples: `navigation_and_routing` and `deeplink-store-example`.   Those two should be simplified into three quickstarts:

- navigation/go_router
- navigation/navigator2
- navigation/deeplinking

- [ ] retire deeplink-store-example
- [ ] simplify navigation_and_routing into navigation/go_router
- [ ] create a simple deeplinking quickstart
- [ ] create a simple navigator2 quickstart
