### ISSUE TITLE
Add Platform Channel sample app

### ISSUE THREAD

**Issue by AyushBherwani1998** [flutter/samples#448]
### Description

The proposal is focusing on adding a sample app demonstrating how to use `MethodChannel`, `EventChannel`, `BasicMessageChannel` and different `MessageCodec`. Apart from a sample app which will live in the main directory, it also focuses on creating a federated plugin example targeting Mobile, Web and Desktop platforms which will reside under the experimental directory.

The proposal is part of GSoC 2020 project.

#### Phase 1
Phase 1 focuses on building a sample app which demonstrates the use of `MethodChannel`, `EventChannel`, `BasicMessageChannel` and `MessageCodec`.

#### Phase 2
Phase 2 focuses on demonstrating how to build a federated plugin which targets Android, Web, Windows and possibly Linux too.
Initially, we were planning to have a battery plugin which supports Android, Web, Windows, and Linux. But, according to [this](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/getBattery) `Navigator.getBattery` is not supported in Safari and Mozilla Firefox. The issue will be updated over the period once we are sure which native functionality will plugin provide.

#### TODO's

- [x] Phase 1
   - [x] Add `MethodChannel` Demo
   - [x] Add `EventChannel` Demo
   - [x] Add `BasicMessageChannel` Demo and use `MessageCodec` to pass different data across platforms.
- [ ] Phase 2
   - [x] Initially create a fedrated plugin for Mobile platform.
   - [x] Add support for Web.
   - [x] Add support for Windows.
   - [ ] Add support for Linux ( if time permits )

cc: @RedBrogdon @domesticmouse

**Comment by mohak852** [comment]
Can I work on this app.

**Comment by AyushBherwani1998** [comment]
Hey @mohak852 👋 
Happy to know you are willing to contribute to the repo, but unfortunately since this project is the part of GSoC 2020, you won't be able to contribute to this project during the GSoC period. Said that we may open up the project for iOS contributors during the GSoC, which is yet not decided. 

Till then, I would suggest looking around more open issues in the repo and send a PR.

**Comment by RedBrogdon** [comment]
@mohak852, as @AyushBherwani1998 mentioned, this work has already been scoped and assigned as a Summer of Code project. If you're interested in contributing to Flutter, there are many ways to do it.

Both [Awesome DartPad](https://github.com/divyanshub024/awesome-dart-pad) and [Awesome Flutter](https://github.com/Solido/awesome-flutter) are great places to join projects and contribute to the community, for instance.

**Comment by josephjw** [comment]
i d like to work on this app

**Comment by ericwindmill** [comment]
This ticket is outdated
